global:
  serviceAccount: 'briefer-sa'
  create_serviceAccount: false
# Set this to false if you are using an external Postgres database (recommended)
enableLocalPostgres: true
ai:
  enabled: true
  replicaCount: 1
  image:
    repository: docker.io
    name: briefercloud/briefer-ai
    tag: v0.0.98
    pullPolicy: Always
  resources:
    requests:
      cpu: 0.5
      memory: 2Gi
    limits:
      cpu: 0.5
      memory: 2Gi
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: briefer.cloud/domain
      #               operator: In
      #               values:
      #                 - core
      # tolerations:
      #   - key: 'briefer.cloud/domain'
      #     operator: 'Equal'
      #     value: 'core'
      #     effect: 'NoSchedule'
web:
  replicaCount: 1
  image:
    repository: docker.io
    name: briefercloud/briefer-web
    tag: v0.0.98
    pullPolicy: Always
  # optional
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 1
      memory: 2Gi
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: briefer.cloud/domain
      #               operator: In
      #               values:
      #                 - core
      #
      # tolerations:
      #   - key: 'briefer.cloud/domain'
      #     operator: 'Equal'
      #     value: 'core'
      #     effect: 'NoSchedule'
api:
  replicaCount: 1
  image:
    repository: docker.io
    name: briefercloud/briefer-api
    tag: v0.0.98
    pullPolicy: Always
  resources:
    requests:
      cpu: 1
      memory: 4Gi
    limits:
      cpu: 1
      memory: 4Gi
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: briefer.cloud/domain
      #               operator: In
      #               values:
      #                 - core
      #
      # tolerations:
      #   - key: 'briefer.cloud/domain'
      #     operator: 'Equal'
      #     value: 'core'
      #     effect: 'NoSchedule'
# use tolerations and affinity to deploy the jupyter pod on a specific node if needed
jupyter:
  storageClassName: gp3
  storageSize: 16Gi
  resources:
    requests:
      cpu: 1
      memory: 4Gi
    limits:
      cpu: 1
      memory: 4Gi
  image:
    repository: docker.io
    name: briefercloud/briefer-jupyter
    tag: v0.0.98
    pullPolicy: Always
# tolerations:
#   - key: 'briefer.cloud/domain'
#     operator: 'Equal'
#     value: 'core'
#     effect: 'NoSchedule'
# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: briefer.cloud/domain
#               operator: In
#               values:
#                 - jupyter
