{{- if .Values.api.ingress.enabled -}}
{{- $fullName := include "briefer.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-api
  labels:
    app.kubernetes.io/name: {{ include "briefer.name" . }}
    helm.sh/chart: {{ include "briefer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.api.ingress.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.api.ingress.ingressClassName | default "alb" }}
  
  # Automatically include TLS if ingress is enabled
  tls:
    {{- range .Values.api.ingress.hosts }}
    - hosts:
        - {{ tpl . $ }}
    {{- end }}
  
  rules:
  {{- range .Values.api.ingress.hosts }}
    - host: {{ tpl . $ }}
      http:
        paths:
          - path: {{ $.Values.api.ingress.path }}
            pathType: {{ $.Values.api.ingress.pathType }}
            backend:
              service:
                name: {{ $fullName }}-api
                port:
                  name: briefer-api
  {{- end }}
{{- end }}
