{{- $serviceTolerations := .Values.ai.tolerations | default (include "briefer.global.tolerations" .) -}}
{{- $serviceAffinity := .Values.ai.affinity | default (include "briefer.global.affinity" .) -}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: '{{ .Release.Namespace }}'
  name: briefer-jupyter
  labels:
    app.kubernetes.io/name: briefer
    app.kubernetes.io/component: jupyter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: briefer
      app.kubernetes.io/component: jupyter
  serviceName: briefer-jupyter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: briefer
        app.kubernetes.io/component: jupyter
    spec:
      # Add security context for the pod
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: jupyter
        image: '{{ .Values.jupyter.image.repository }}/{{ .Values.jupyter.image.name }}:{{ .Values.jupyter.image.tag }}'
        command:
          - "sh"
          - "-c"
          - "jupyter server --ip=0.0.0.0 --ZMQChannelsWebsocketConnection.iopub_data_rate_limit=1.0e10 --ZMQChannelsWebsocketConnection.iopub_msg_rate_limit=1.0e6 --ServerApp.max_body_size=107374182400"
        # Add security context for the container
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
        {{- if .Values.jupyter.resources }}
        resources:
          {{- with .Values.jupyter.resources.requests }}
          requests:
            {{- if .memory }}
            memory: {{ .memory | quote }}
            {{- end }}
            {{- if .cpu }}
            cpu: {{ .cpu | quote }}
            {{- end }}
          {{- end }}
          {{- with .Values.jupyter.resources.limits }}
          limits:
            {{- if .memory }}
            memory: {{ .memory | quote }}
            {{- end }}
            {{- if .cpu }}
            cpu: {{ .cpu | quote }}
            {{- end }}
          {{- end }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /api
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 5
          timeoutSeconds: 10
        env:
        - name: JUPYTER_TOKEN
          valueFrom:
            secretKeyRef:
              name: briefer-env
              key: JUPYTERTOKEN
        ports:
        - containerPort: 8888
          name: jupyter-port
        volumeMounts:
        - name: jupyter-storage
          mountPath: /home/jupyteruser
      {{- if $serviceAffinity }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            {{- range $serviceAffinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms }}
            - matchExpressions:
              {{- range .matchExpressions }}
              - key: {{ .key }}
                operator: {{ .operator }}
                {{- if .values }}
                values:
                {{- range .values }}
                - {{ . }}
                {{- end }}
                {{- end }}
              {{- end }}
            {{- end }}
      {{- end }}

      {{- if $serviceTolerations }}
      tolerations:
        {{- range $serviceTolerations }}
        - key: {{ .key }}
          operator: {{ .operator }}
          {{- if .value }}
          value: {{ .value }}
          {{- end }}
          effect: {{ .effect }}
        {{- end }}
      {{- end }}

  volumeClaimTemplates:
  - metadata:
      name: jupyter-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "{{ .Values.jupyter.storageClassName | default "gp3" }}"
      resources:
        requests:
          storage: "{{ .Values.jupyter.storageSize | default "16Gi" }}"
