{{- $globalSA := .Values.global.serviceAccount }}
{{- $createSA := .Values.global.create_serviceAccount | default false }}

{{- if $createSA }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.web.serviceAccount | default $globalSA | default (printf "%-web" .Release.Name) }}
  namespace: '{{ .Release.Namespace }}'
{{- end }}
