{{- if .Values.web.ingress.enabled -}}
{{- $fullName := include "briefer.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-web
  labels:
    app.kubernetes.io/name: {{ include "briefer.name" . }}
    helm.sh/chart: {{ include "briefer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.web.ingress.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
{{- end }}
spec:
{{- with .Values.web.ingress.ingressClassName }}
  ingressClassName: {{ . }}
{{- end }}
  tls:
    - hosts:
      {{- range .Values.web.ingress.hosts }}
        - {{ tpl . $ | quote }}
      {{- end }}
  rules:
  {{- range .Values.web.ingress.hosts }}
    - host: {{ tpl . $ | quote }}
      http:
        paths:
          - path: {{ $.Values.web.ingress.path }}
            pathType: {{ $.Values.web.ingress.pathType }}
            backend:
              service:
                name: {{ $fullName }}-web
                port:
                  name: briefer-web
  {{- end }}
