{{- $serviceSA := .Values.web.serviceAccount | default (include "briefer.global.serviceAccount" .) -}}
{{- $serviceTolerations := .Values.web.tolerations | default (include "briefer.global.tolerations" .) -}}
{{- $serviceAffinity := .Values.web.affinity | default (include "briefer.global.affinity" .) -}}

apiVersion: apps/v1

kind: Deployment
metadata:
  name: web-deployment
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/name: briefer
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: briefer
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: briefer
        app.kubernetes.io/component: web
    spec:
      serviceAccountName: {{ $serviceSA }}
      containers:
        - name: web
          image: '{{ .Values.web.image.repository }}/{{ .Values.web.image.name }}:{{ .Values.web.image.tag }}'
          imagePullPolicy: '{{ .Values.web.image.pullPolicy | default "Always" }}'
          {{- if .Values.web.resources }}
          resources:
            {{- with .Values.web.resources.requests }}
            requests:
              {{- if .memory }}
              memory: {{ .memory | quote }}
              {{- end }}
              {{- if .cpu }}
              cpu: {{ .cpu | quote }}
              {{- end }}
            {{- end }}
            {{- with .Values.web.resources.limits }}
            limits:
              {{- if .memory }}
              memory: {{ .memory | quote }}
              {{- end }}
              {{- if .cpu }}
              cpu: {{ .cpu | quote }}
              {{- end }}
            {{- end }}
          {{- end }}
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: briefer-env
                  key: NODE_ENV
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                secretKeyRef:
                  name: briefer-env
                  key: NEXT_PUBLIC_API_URL
            - name: NEXT_PUBLIC_API_WS_URL
              valueFrom:
                secretKeyRef:
                  name: briefer-env
                  key: NEXT_PUBLIC_API_WS_URL
            - name: NEXT_PUBLIC_PUBLIC_URL
              valueFrom:
                secretKeyRef:
                  name: briefer-env
                  key: NEXT_PUBLIC_PUBLIC_URL

      {{- if $serviceAffinity }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            {{- range $serviceAffinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms }}
            - matchExpressions:
              {{- range .matchExpressions }}
              - key: {{ .key }}
                operator: {{ .operator }}
                {{- if .values }}
                values:
                {{- range .values }}
                - {{ . }}
                {{- end }}
                {{- end }}
              {{- end }}
            {{- end }}
      {{- end }}

      {{- if $serviceTolerations }}
      tolerations:
        {{- range $serviceTolerations }}
        - key: {{ .key }}
          operator: {{ .operator }}
          {{- if .value }}
          value: {{ .value }}
          {{- end }}
          effect: {{ .effect }}
        {{- end }}
      {{- end }}
